app/urls.py
from django.urls import path
from .views import Home

app_name = 'app'

urlpatterns = [
    path('', Home.as_view(), name="home"),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('usuarios/', include('usuarios.urls')),
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.login, name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('criar-conta/', views.criar_conta, name="criar-conta"),
    path('trocar-senha/', views.TrocarSenha.as_view(), name="trocar-senha"),
    # resetar senha
    path('esqueceu-senha-form/', views.EsqueceuSenhaFormView.as_view(), name="esqueceu-senha-form"),
    # path('esqueceu-senha-msg/', views.EsqueceuSenhaMsg.as_view(), name="esqueceu-senha-msg"),
    path('esqueceu-senha-link/<uidb64>/<token>/', views.EsqueceuSenhaLink.as_view(), name="esqueceu-senha-link"),
    # path('senha-alterada/', views.SenhaAlterada.as_view(), name="senha-alterada"),

    path(r'^ativar-conta/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.ativar_conta, name='ativar-conta'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html class="h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="icon" type="image/x-icon" href=" static 'core/img/logo.ico'"> -->
  <!-- <link rel="apple-touch-icon" href=" static 'core/img/apple-touch-icon-iphone-60x60.png' ">
  <link rel="apple-touch-icon" sizes="60x60" href=" static 'core/img/apple-touch-icon-ipad-76x76.png' ">
  <link rel="apple-touch-icon" sizes="114x114" href=" static 'core/img/apple-touch-icon-iphone-retina-120x120.png' ">
  <link rel="apple-touch-icon" sizes="144x144" href=" static 'core/img/apple-touch-icon-ipad-retina-152x152.png' "> -->
  
  <title>APP</title>
  
  <!-- Bootstrap core CSS and icons -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  
</head>
    {% block content %}
    {% endblock %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</html>

core/templates/core/mensagens.html
{% if messages %}
    {% for message in messages %}
    <div class="d-flex justify-content-center" id="id_message">
      <div class="alert alert-{{message.tags}} text-center col alert-dismissible" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}
{% endif %}

core/templates/core/menu.html
<nav class="navbar navbar-expand-lg border-bottom">
  <div class="container py-2">
    <img class="mb-2" src="https://via.placeholder.com/200x50">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav fs-4 ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:home' %}">Início</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Para empresas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'usuarios:login' %}">Minha conta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-warning" href="#">Contratar</a>
        </li>
      </ul>
    </div>
  </div>
</nav>