app/urls.py
from django.urls import path
from .views import Home

app_name = 'app'

urlpatterns = [
    path('', Home.as_view(), name="home"),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('usuarios/', include('usuarios.urls')),
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.login, name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('criar-conta/', views.criar_conta, name="criar-conta"),
    path('trocar-senha/', views.TrocarSenha.as_view(), name="trocar-senha"),
    # resetar senha
    path('esqueceu-senha-form/', views.EsqueceuSenhaFormView.as_view(), name="esqueceu-senha-form"),
    # path('esqueceu-senha-msg/', views.EsqueceuSenhaMsg.as_view(), name="esqueceu-senha-msg"),
    path('esqueceu-senha-link/<uidb64>/<token>/', views.EsqueceuSenhaLink.as_view(), name="esqueceu-senha-link"),
    # path('senha-alterada/', views.SenhaAlterada.as_view(), name="senha-alterada"),

    path(r'^ativar-conta/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.ativar_conta, name='ativar-conta'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):

    username = models.CharField(max_length=20, unique=True, verbose_name='Username')
    first_name = models.CharField(max_length=20, verbose_name='Primeiro nome')
    last_name = models.CharField(max_length=20, verbose_name='Último nome')
    email = models.EmailField(verbose_name='E-mail', unique=True)

    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.get_full_name()

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from .models import Usuario
from django import forms


class RegistraUsuarioForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=50, label='Primeiro nome', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=50, label='Último nome', widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Usuario
        fields = ['username', 'email', 'first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['username'].label = 'Nome de usuário'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

        # TODO is_staff
        # TODO adicionar CNPJ e nome do cliente


class TrocaSenhaForm(PasswordChangeForm):
    old_password = forms.CharField(label='Senha antiga', min_length=8,
                                   widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(
        label='Nova senha', min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(
        label='Confirmação', min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Usuario
        fields = ['old_password', 'new_password1', 'new_password2']


class EsqueceuSenhaForm(PasswordResetForm):
    email = forms.EmailField(
        label=('Email'),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", 'class': 'form-control'}),
    )


class EsqueceuSenhaLinkForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label=('Nova senha'),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}),
        strip=False,
        # help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=('Confirmação'),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}),
    )

usuarios/views.py
from django.contrib import auth, messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.views import PasswordChangeView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from usuarios.models import Usuario
from usuarios.forms import RegistraUsuarioForm, TrocaSenhaForm, EsqueceuSenhaForm, EsqueceuSenhaLinkForm
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage


def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        if email == '' or password == '':
            messages.error(
                request, 'Os campos email e senha não podem ser vazios')
            return redirect('usuarios:login')

        if Usuario.objects.filter(email=email).exists():
            username = Usuario.objects.get(email=email).username
            user = auth.authenticate(
                request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('app:home')
            else:
                messages.error(request, 'Usuário não cadastrado')
                return redirect('usuarios:login')
        else:
            messages.error(request, 'Usuário não cadastrado')

    return render(request, 'usuarios/login.html')


class Logout(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('app:home')


def criar_conta(request):
    if request.user.is_anonymous:
        if request.method == 'POST':
            form = RegistraUsuarioForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                email = form.cleaned_data.get('email')
                first_name = form.cleaned_data.get('first_name')
                last_name = form.cleaned_data.get('last_name')
                password1 = form.cleaned_data.get('password1')
                password2 = form.cleaned_data.get('password2')
                usuario = form.save(commit=False)
                usuario.is_active = False
                usuario.save()
                current_site = get_current_site(request)
                message = render_to_string('usuarios/email-ativacao.html', {
                    'usuario': usuario, 'dominio': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
                    'token': account_activation_token.make_token(usuario),
                })

                # Sending activation link in terminal
                subject = 'Ative a sua conta'
                usuario.email_user(subject, message)
                # mail_subject = 'Activate your blog account.'
                # to_email = form.cleaned_data.get('email')
                # email = EmailMessage(mail_subject, message, to=[to_email])
                # email.send()
                return HttpResponse('Por favor confirme seu endereço de email para ativar sua conta.')
                # return render(request, 'email-ativacao.html')

            else:
                return render(request, 'usuarios/criar-conta.html', {'form': form})
        else:
            form = RegistraUsuarioForm()
            return render(request, 'usuarios/criar-conta.html', {'form': form})
    else:
        return redirect('app:home')


def ativar_conta(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        usuario = Usuario.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Usuario.DoesNotExist):
        usuario = None
    if usuario is not None and account_activation_token.check_token(usuario, token):
        usuario.is_active = True
        usuario.save()
        auth_login(request, usuario)
        return HttpResponse('Obrigado por confirmar seu e-mail. Agora você pode fazer login.')
    else:
        return HttpResponse('Link de ativação inválido!')


class TrocarSenha(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    form_class = TrocaSenhaForm
    template_name = 'usuarios/trocar-senha.html'
    success_url = reverse_lazy('app:home')
    success_message = 'Senha alterada com sucesso'


class EsqueceuSenhaFormView(SuccessMessageMixin, PasswordResetView):
    template_name = 'usuarios/esqueceu-senha-form.html'
    form_class = EsqueceuSenhaForm
    email_template_name = 'usuarios/corpo-email-esqueceu-senha.html'
    # html_email_template_name = 'usuarios/corpo-email-esqueceu-senha.html'
    from_email = 'tiberio.mendonca@meucontato.app.br'
    subject_template_name = "usuarios/assunto.txt"
    success_url = reverse_lazy('usuarios:login')
    success_message = 'Enviamos um e-mail com instruções para definir sua senha, se uma conta existe com o e-mail que você digitou você deve recebê-lo em breve.'


# class EsqueceuSenhaMsg(PasswordResetDoneView):
#     template_name = "usuarios/esqueceu-senha-msg.html"

class EsqueceuSenhaLink(SuccessMessageMixin, PasswordResetConfirmView):
    form_class = EsqueceuSenhaLinkForm
    success_url = reverse_lazy("usuarios:login")
    template_name = "usuarios/esqueceu-senha-link.html"
    success_message = 'Sua senha foi definida. Você pode ir em frente e fazer login agora.'

# class SenhaAlterada(PasswordResetCompleteView):
#     template_name = "usuarios/senha-alterada.html"

# novo_usuario = authenticate(
    #     username=username, password=password1)
    # if novo_usuario is not None:
    #     auth_login(request, novo_usuario)
    #     messages.success(
    #         request, 'Conta criada com sucesso! Acesse o seu email e click no link de confirmação para validar sua conta')
    #     return redirect('app:home')# novo_usuario = authenticate(
    #     username=username, password=password1)
    # if novo_usuario is not None:
    #     auth_login(request, novo_usuario)
    #     messages.success(
    #         request, 'Conta criada com sucesso! Acesse o seu email e click no link de confirmação para validar sua conta')
    #     return redirect('app:home')


# def signup(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.is_active = False
#             user.save()
#             current_site = get_current_site(request)
#             message = render_to_string('acc_active_email.html', {
#                 'user': user, 'domain': current_site.domain,
#                 'uid': urlsafe_base64_encode(force_bytes(user.pk)),
#                 'token': account_activation_token.make_token(user),
#             })
#             # Sending activation link in terminal
#             # user.email_user(subject, message)
#             mail_subject = 'Activate your blog account.'
#             to_email = form.cleaned_data.get('email')
#             email = EmailMessage(mail_subject, message, to=[to_email])
#             email.send()
#             return HttpResponse('Please confirm your email address to complete the registration.')
#             # return render(request, 'acc_active_sent.html')
#     else:
#         form = SignupForm()
#     return render(request, 'signup.html', {'form': form})

usuarios/templates/usuarios/corpo-email-esqueceu-senha.html
{% autoescape off %}

Alguém solicitou uma recuperação de senha para o email {{ email }}. Clique no link abaixo para criar uma nova senha:
{{ protocol}}://{{ domain }}{% url 'usuarios:esqueceu-senha-link' uidb64=uid token=token %}

Esse link somente pode ser utilizado uma vez.

Se não foi você que solicitou uma troca de senha, você pode ignorar essa mensagem.


Atenciosamente,

Equipe APP

{% endautoescape %}

usuarios/templates/usuarios/criar-conta.html
{% extends 'core/base.html' %}
{% block content %}

<body class="container d-flex flex-column h-100 justify-content-center align-items-center">

  <form action="{% url 'usuarios:criar-conta' %}" method="post" class="col col-lg-4 p-4">
    {% csrf_token %}
    {% for field in form %}
    <p>
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <div class="alert alert-danger text-center alert-dismissible" role="alert">
          {{error}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </p>
    {% endfor %}
    <button type="submit" class="btn btn-primary w-100">Criar conta</button>
  </form>

</body>
{% endblock %}

usuarios/templates/usuarios/email-ativacao.html
{% autoescape off %}
Olá {{ usuario.username }},
Por favor clique no link abaixo para ativar a sua conta,
http://{{ dominio }}{% url 'usuarios:ativar-conta' uidb64=uid token=token %}
{% endautoescape %}

usuarios/templates/usuarios/esqueceu-senha-form.html
{% extends 'core/base.html' %}
{% block content %}

<body class="container d-flex flex-column h-100 justify-content-center align-items-center">

  <form action="{% url 'usuarios:esqueceu-senha-form' %}" method="post" class="col-lg-4">
    {% csrf_token %}
    {% for field in form %}
    <p>
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <div class="alert alert-danger text-center alert-dismissible" role="alert">
          {{error}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </p>
    {% endfor %}
    <button type="submit" class="btn btn-primary w-100">Enviar</button>
  </form>

</body>
{% endblock %}

usuarios/templates/usuarios/esqueceu-senha-link.html
{% extends 'core/base.html' %}
{% block content %}

<body class="container d-flex flex-column h-100 justify-content-center align-items-center">
  <form method="post" class="col-4">
    {% csrf_token %}

    {% include 'core/mensagens.html' %}

    {% for field in form %}
    <p>
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
      <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <div class="alert alert-danger text-center alert-dismissible" role="alert">
          {{error}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </p>
    {% endfor %}
    <ul>
      <li>Sua senha não pode ser similiar a alguma informação pessoal</li>
      <li>Sua senha deve conter pelo menos 8 caracteres</li>
      <li>Sua senha não pode ser uma senha muito comum</li>
      <li>Sua senha não pode ser inteiramente numérica</li>
    </ul>
    <button type="submit" class="btn btn-primary w-100">Salvar</button>
  </form>
</body>
{% endblock %}

usuarios/templates/usuarios/esqueceu-senha-msg.html
Enviamos um e-mail com instruções para definir sua senha, se uma conta existe com o e-mail que você digitou você deve recebê-lo em breve.

usuarios/templates/usuarios/login.html
{% extends 'core/base.html' %}
{% block content %}
<body class="container d-flex flex-column h-100 justify-content-center align-items-center">
  <form action="{% url 'usuarios:login' %}" method="post" class="text-center col-lg-4">
    {% csrf_token %}
      <div class="mb-3">
        <img src="https://via.placeholder.com/150" />
      </div>
    
      {% include 'core/mensagens.html' %}
    
      <div class="mb-1">
        <input type="text" id="email" class="form-control" name="email" placeholder="Email">
      </div>
      <div class="mb-3">
        <input type="password" id="password" class="form-control" name="password" placeholder="Senha">
      </div>
      <button type="submit" class="btn btn-primary w-100">Login</button>
  </form>
  <a href="{% url 'usuarios:criar-conta' %}" class="text-decoration-none">Criar conta</a>
  <a href="{% url 'usuarios:esqueceu-senha-form' %}" class="text-decoration-none">Esqueci a senha</a>
</body>
{% endblock %}

usuarios/templates/usuarios/senha-alterada.html
"Sua senha foi definida. Você pode ir em frente e fazer login agora."

usuarios/templates/usuarios/trocar-senha.html
{% extends 'core/base.html' %}
{% block content %}

<body class="container d-flex flex-column h-100 justify-content-center align-items-center">
  <form method="post" class="col-4">
    {% csrf_token %}

    {% include 'core/mensagens.html' %}

    {% for field in form %}
    <p>
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
      <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <div class="alert alert-danger text-center alert-dismissible" role="alert">
          {{error}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </p>
    {% endfor %}
    <ul>
      <li>Sua senha não pode ser similiar a alguma informação pessoal</li>
      <li>Sua senha deve conter pelo menos 8 caracteres</li>
      <li>Sua senha não pode ser uma senha muito comum</li>
      <li>Sua senha não pode ser inteiramente numérica</li>
    </ul>
    <button type="submit" class="btn btn-primary w-100">Salvar</button>
  </form>
</body>
{% endblock %}